/**
 * Thin wrappers around TanStack Query hooks for server functions.
 *
 * These accept a server function directly and auto-generate queryKey + queryFn
 * using the build-time fnId. For non-server-function usage, import the raw
 * TanStack hooks from `@tanstack/react-query`.
 *
 * @example
 * const { data } = useQuery(getUsers);
 * const { data } = useQuery(getUser, userId);
 * const { mutate } = useMutation(createUser, { invalidates: [getUsers] });
 */

import type {
  UseMutationOptions,
  UseMutationResult,
  UseQueryResult,
} from "@tanstack/react-query";
import {
  useMutation as tanstackUseMutation,
  useQuery as tanstackUseQuery,
  useQueryClient,
} from "@tanstack/react-query";
import { __fn_call, getFnId } from "./transport";

/**
 * A server function stub as generated by the build-tools loader.
 */
export type ServerFunction<TArgs extends unknown[], TResponse> = (
  ...args: TArgs
) => Promise<TResponse>;

// biome-ignore lint/suspicious/noExplicitAny: must accept any function shape
type AnyFunction = (...args: any[]) => any;

/** Derive a stable key from a server function's build-time fnId. */
export function getBaseKey(fn: AnyFunction): string {
  return getFnId(fn) || fn.name || "unknown";
}

/** Build queryFn using RPC transport. */
export function buildQueryFn(
  fn: AnyFunction,
  args: unknown[],
): (ctx: { signal: AbortSignal }) => Promise<unknown> {
  const fnId = getFnId(fn);
  if (fnId) {
    return ({ signal }) => __fn_call(fnId, args, { signal });
  }
  return () => fn(...args) as Promise<unknown>;
}

// ---------------------------------------------------------------------------
// useQuery
// ---------------------------------------------------------------------------

/**
 * `useQuery` for server functions — auto-generates queryKey + queryFn.
 *
 * @example
 * useQuery(getUsers);
 * useQuery(getUser, userId);
 */
export function useQuery<TData = unknown, TError = Error>(
  fn: AnyFunction,
  ...args: unknown[]
): UseQueryResult<TData, TError> {
  const baseKey = getBaseKey(fn);
  return tanstackUseQuery<TData, TError>({
    queryKey: [baseKey, ...args],
    queryFn: buildQueryFn(fn, args) as () => Promise<TData>,
  });
}

// ---------------------------------------------------------------------------
// useMutation
// ---------------------------------------------------------------------------

/**
 * `useMutation` for server functions — auto-generates mutationFn.
 *
 * @example
 * const { mutate } = useMutation(createUser);
 * const { mutate } = useMutation(createUser, { invalidates: [getUsers] });
 */
export function useMutation<
  TData = unknown,
  TError = Error,
  TVariables = unknown,
>(
  fn: AnyFunction,
  options?: Omit<
    UseMutationOptions<TData, TError, TVariables>,
    "mutationFn"
  > & {
    /** Server functions whose queries should be invalidated on success. */
    invalidates?: AnyFunction[];
  },
): UseMutationResult<TData, TError, TVariables> {
  const queryClient = useQueryClient();
  const { invalidates, ...restOptions } = options ?? {};
  return tanstackUseMutation<TData, TError, TVariables>({
    ...(restOptions as Omit<
      UseMutationOptions<TData, TError, TVariables>,
      "mutationFn"
    >),
    mutationFn: (variables: TVariables) => fn(variables) as Promise<TData>,
    onSuccess: (...onSuccessArgs) => {
      if (invalidates) {
        for (const target of invalidates) {
          const targetKey = getBaseKey(target);
          queryClient.invalidateQueries({ queryKey: [targetKey] });
        }
      }
      (
        restOptions as UseMutationOptions<TData, TError, TVariables>
      )?.onSuccess?.(...onSuccessArgs);
    },
  });
}
