import {
  type UseMutationOptions,
  type UseMutationResult,
  type UseQueryOptions,
  type UseQueryResult,
  type UseSuspenseQueryOptions,
  type UseSuspenseQueryResult,
  useMutation,
  useQuery,
  useSuspenseQuery,
} from "@tanstack/react-query";

/**
 * A server function stub as generated by the evjs webpack loader.
 */
export type ServerFunction<TArgs extends unknown[], TResponse> = ((
  ...args: TArgs
) => Promise<TResponse>) & {
  _evId?: string;
};

/**
 * The interface for a single server function's query proxy.
 */
export interface QueryProxyHandler<TArgs extends unknown[], TResponse> {
  /** Call the server function directly. */
  (...args: TArgs): Promise<TResponse>;

  /** Use as a standard TanStack Query. */
  useQuery(
    args: TArgs,
    options?: Omit<UseQueryOptions<TResponse, Error>, "queryKey" | "queryFn">,
  ): UseQueryResult<TResponse, Error>;

  /** Use as a TanStack Suspense Query. */
  useSuspenseQuery(
    args: TArgs,
    options?: Omit<
      UseSuspenseQueryOptions<TResponse, Error>,
      "queryKey" | "queryFn"
    >,
  ): UseSuspenseQueryResult<TResponse, Error>;

  /** Returns standard TanStack Query options. */
  queryOptions(
    args: TArgs,
    options?: Omit<UseQueryOptions<TResponse, Error>, "queryKey" | "queryFn">,
  ): UseQueryOptions<TResponse, Error> & {
    queryKey: unknown[];
    queryFn: () => Promise<TResponse>;
  };

  /** Returns the query key for this function and arguments. */
  queryKey(args?: TArgs): unknown[];

  /** The stable function ID (internal). */
  _evId: string;
}

/**
 * The interface for a single server function's mutation proxy.
 */
export interface MutationProxyHandler<TVariables, TResponse> {
  /** Call the server function directly. */
  (variables: TVariables): Promise<TResponse>;

  /** Use as a TanStack Mutation. */
  useMutation(
    options?: Omit<
      UseMutationOptions<TResponse, Error, TVariables>,
      "mutationFn"
    >,
  ): UseMutationResult<TResponse, Error, TVariables>;

  /** Returns standard TanStack Mutation options. */
  mutationOptions(
    options?: Omit<
      UseMutationOptions<TResponse, Error, TVariables>,
      "mutationFn"
    >,
  ): UseMutationOptions<TResponse, Error, TVariables> & {
    mutationFn: (variables: TVariables) => Promise<TResponse>;
  };

  /** The stable function ID (internal). */
  _evId: string;
}

/**
 * A recursive proxy that maps property access to server function stubs.
 */
export type QueryProxy<TModule> = {
  [K in keyof TModule]: TModule[K] extends ServerFunction<
    infer TArgs,
    infer TResponse
  >
    ? QueryProxyHandler<TArgs, TResponse>
    : QueryProxy<TModule[K]>;
};

export type MutationProxy<TModule> = {
  [K in keyof TModule]: TModule[K] extends ServerFunction<
    infer TVars,
    infer TResponse
  >
    ? MutationProxyHandler<TVars, TResponse>
    : MutationProxy<TModule[K]>;
};

function createHandler(fn: ServerFunction<unknown[], unknown>, path: string[]) {
  return {
    useQuery: (
      args: unknown[] = [],
      options?: Omit<UseQueryOptions<unknown, Error>, "queryKey" | "queryFn">,
    ) => {
      return useQuery({
        ...options,
        queryKey: [fn._evId || path.join("."), ...args],
        queryFn: () => fn(...args),
      });
    },
    useSuspenseQuery: (
      args: unknown[] = [],
      options?: Omit<
        UseSuspenseQueryOptions<unknown, Error>,
        "queryKey" | "queryFn"
      >,
    ) => {
      return useSuspenseQuery({
        ...options,
        queryKey: [fn._evId || path.join("."), ...args],
        queryFn: () => fn(...args),
      });
    },
    useMutation: (
      options?: Omit<UseMutationOptions<unknown, Error, unknown>, "mutationFn">,
    ) => {
      return useMutation({
        ...options,
        mutationFn: (variables: unknown) => fn(variables),
      });
    },
    queryOptions: (
      args: unknown[] = [],
      options?: Omit<UseQueryOptions<unknown, Error>, "queryKey" | "queryFn">,
    ) => {
      return {
        ...options,
        queryKey: [fn._evId || path.join("."), ...args],
        queryFn: () => fn(...args),
      };
    },
    mutationOptions: (
      options?: Omit<UseMutationOptions<unknown, Error, unknown>, "mutationFn">,
    ) => {
      return {
        ...options,
        mutationFn: (variables: unknown) => fn(variables),
      };
    },
    queryKey: (args: unknown[] = []) => {
      return [fn._evId || path.join("."), ...args];
    },
    _evId: fn._evId,
    path: path.join("."),
  };
}

function createProxy(
  type: "query" | "mutation",
  source?: unknown,
  path: string[] = [],
): unknown {
  const target = source ?? (() => {});
  return new Proxy(target as object, {
    get(_target, prop: string) {
      if (prop === "_evId") return (_target as { _evId?: string })._evId;

      const newPath = [...path, prop];
      const val = source
        ? (source as Record<string, unknown>)[prop]
        : undefined;

      // If we have a source and this is a function, return the handler
      if (typeof val === "function") {
        return createHandler(
          val as unknown as ServerFunction<unknown[], unknown>,
          newPath,
        );
      }

      // Otherwise return a nested proxy
      return createProxy(type, val, newPath);
    },
    apply(_target, _thisArg, args) {
      const fn = args[0] as unknown as ServerFunction<unknown[], unknown>;
      if (typeof fn === "function") {
        return createHandler(fn, path);
      }
      return fn; // Fallback
    },
  });
}

/**
 * Create a type-safe query proxy for a module or object.
 */
export function createQueryProxy<T>(source?: T): QueryProxy<T> {
  return createProxy("query", source) as QueryProxy<T>;
}

/**
 * Create a type-safe mutation proxy for a module or object.
 */
export function createMutationProxy<T>(source?: T): MutationProxy<T> {
  return createProxy("mutation", source) as MutationProxy<T>;
}

/**
 * The global query proxy/wrapper.
 * @example
 * const { data } = query(getUsers).useQuery();
 * // or with a typed proxy:
 * const api = createQueryProxy(getUsersModule);
 * const { data } = api.getUsers.useQuery();
 */
export const query = createProxy("query") as (<
  TArgs extends unknown[],
  TResponse,
>(
  fn: ServerFunction<TArgs, TResponse>,
) => QueryProxyHandler<TArgs, TResponse>) &
  QueryProxy<Record<string, unknown>>;

/**
 * The global mutation proxy/wrapper.
 * @example const { mutate } = mutation(createUser).useMutation();
 */
export const mutation = createProxy("mutation") as (<TVariables, TResponse>(
  fn: (args: TVariables) => Promise<TResponse>,
) => MutationProxyHandler<TVariables, TResponse>) &
  MutationProxy<Record<string, unknown>>;
