import {
  useQuery,
  useSuspenseQuery,
  useMutation,
  type UseQueryOptions,
  type UseSuspenseQueryOptions,
  type UseMutationOptions,
  type UseQueryResult,
  type UseSuspenseQueryResult,
  type UseMutationResult,
} from "@tanstack/react-query";

/**
 * A server function stub as generated by the evjs webpack loader.
 */
export type ServerFunction<TArgs extends any[], TResponse> = ((
  ...args: TArgs
) => Promise<TResponse>) & {
  evId?: string;
};

// ── Proxy Types ──────────────────────────────────────────

/**
 * The interface for a single server function's query proxy.
 */
export interface QueryProxyHandler<TArgs extends any[], TResponse> {
  /** Call the server function directly. */
  (...args: TArgs): Promise<TResponse>;

  /** Use as a standard TanStack Query. */
  useQuery(
    args: TArgs,
    options?: Omit<UseQueryOptions<TResponse, Error>, "queryKey" | "queryFn">
  ): UseQueryResult<TResponse, Error>;

  /** Use as a TanStack Suspense Query. */
  useSuspenseQuery(
    args: TArgs,
    options?: Omit<
      UseSuspenseQueryOptions<TResponse, Error>,
      "queryKey" | "queryFn"
    >
  ): UseSuspenseQueryResult<TResponse, Error>;

  /** Returns standard TanStack Query options. */
  queryOptions(
    args: TArgs,
    options?: Omit<UseQueryOptions<TResponse, Error>, "queryKey" | "queryFn">
  ): UseQueryOptions<TResponse, Error> & { queryKey: any[]; queryFn: any };

  /** The stable function ID. */
  evId: string;
}

/**
 * The interface for a single server function's mutation proxy.
 */
export interface MutationProxyHandler<TVariables, TResponse> {
  /** Call the server function directly. */
  (variables: TVariables): Promise<TResponse>;

  /** Use as a TanStack Mutation. */
  useMutation(
    options?: Omit<
      UseMutationOptions<TResponse, Error, TVariables>,
      "mutationFn"
    >
  ): UseMutationResult<TResponse, Error, TVariables>;

  /** Returns standard TanStack Mutation options. */
  mutationOptions(
    options?: Omit<
      UseMutationOptions<TResponse, Error, TVariables>,
      "mutationFn"
    >
  ): UseMutationOptions<TResponse, Error, TVariables> & { mutationFn: any };

  /** The stable function ID. */
  evId: string;
}

/**
 * A recursive proxy that maps property access to server function stubs.
 */
export type QueryProxy<TModule> = {
  [K in keyof TModule]: TModule[K] extends ServerFunction<
    infer TArgs,
    infer TResponse
  >
  ? QueryProxyHandler<TArgs, TResponse>
  : QueryProxy<TModule[K]>;
};

export type MutationProxy<TModule> = {
  [K in keyof TModule]: TModule[K] extends ServerFunction<
    infer TVars,
    infer TResponse
  >
  ? MutationProxyHandler<TVars, TResponse>
  : MutationProxy<TModule[K]>;
};

// ── Implementation ───────────────────────────────────────

function createHandler(fn: any, path: string[]) {
  return {
    useQuery: (args: any[] = [], options?: any) => {
      return useQuery({
        ...options,
        queryKey: [fn.evId || path.join("."), ...args],
        queryFn: () => fn(...args),
      });
    },
    useSuspenseQuery: (args: any[] = [], options?: any) => {
      return useSuspenseQuery({
        ...options,
        queryKey: [fn.evId || path.join("."), ...args],
        queryFn: () => fn(...args),
      });
    },
    useMutation: (options?: any) => {
      return useMutation({
        ...options,
        mutationFn: (variables: any) => fn(variables),
      });
    },
    queryOptions: (args: any[] = [], options?: any) => {
      return {
        ...options,
        queryKey: [fn.evId || path.join("."), ...args],
        queryFn: () => fn(...args),
      };
    },
    mutationOptions: (options?: any) => {
      return {
        ...options,
        mutationFn: (variables: any) => fn(variables),
      };
    },
    evId: fn.evId,
    path: path.join("."),
  };
}

function createProxy(type: "query" | "mutation", source?: any, path: string[] = []): any {
  const target = source ?? (() => { });
  return new Proxy(target, {
    get(_target, prop: string) {
      if (prop === "evId") return (_target as any).evId;

      const newPath = [...path, prop];
      const val = source ? source[prop] : undefined;

      // If we have a source and this is a function, return the handler
      if (typeof val === "function") {
        return createHandler(val, newPath);
      }

      // Otherwise return a nested proxy
      return createProxy(type, val, newPath);
    },
    apply(_target, _thisArg, args) {
      const fn = args[0];
      if (typeof fn === "function") {
        return createHandler(fn, path);
      }
      return fn; // Fallback
    }
  });
}

/**
 * Create a type-safe query proxy for a module or object.
 */
export function createEvQueryProxy<T>(source?: T): QueryProxy<T> {
  return createProxy("query", source) as QueryProxy<T>;
}

/**
 * Create a type-safe mutation proxy for a module or object.
 */
export function createEvMutationProxy<T>(source?: T): MutationProxy<T> {
  return createProxy("mutation", source) as MutationProxy<T>;
}

/**
 * The global query proxy/wrapper.
 * @example 
 * const { data } = query(getUsers).useQuery();
 * // or with a typed proxy:
 * const api = createEvQueryProxy(getUsersModule);
 * const { data } = api.getUsers.useQuery();
 */
export const query = createProxy("query") as {
  <TArgs extends any[], TResponse>(fn: ServerFunction<TArgs, TResponse>): QueryProxyHandler<TArgs, TResponse>;
} & QueryProxy<any>;

/**
 * The global mutation proxy/wrapper.
 * @example const { mutate } = mutation(createUser).useMutation();
 */
export const mutation = createProxy("mutation") as {
  <TVariables, TResponse>(fn: (args: TVariables) => Promise<TResponse>): MutationProxyHandler<TVariables, TResponse>;
} & MutationProxy<any>;

// ── Legacy Hooks (deprecated) ──────────────────────────

/** @deprecated Use query.fnName.useQuery() */
export function useServerQuery<TArgs extends any[], TResponse, TError = Error>(
  serverFn: ServerFunction<TArgs, TResponse>,
  args: TArgs,
  options?: Omit<UseQueryOptions<TResponse, TError>, "queryKey" | "queryFn">
): UseQueryResult<TResponse, TError> {
  const queryKey = [serverFn.evId || serverFn.name, ...args];
  return useQuery({
    ...options,
    queryKey,
    queryFn: () => serverFn(...args),
  });
}

/** @deprecated Use mutation.fnName.useMutation() */
export function useServerMutation<TVariables, TResponse, TError = Error>(
  serverFn: (args: TVariables) => Promise<TResponse>,
  options?: Omit<UseMutationOptions<TResponse, TError, TVariables>, "mutationFn">
): UseMutationResult<TResponse, TError, TVariables> {
  return useMutation({
    ...options,
    mutationFn: (variables: TVariables) => serverFn(variables),
  });
}
