import {
  type UseMutationOptions,
  type UseMutationResult,
  type UseQueryOptions,
  type UseQueryResult,
  type UseSuspenseQueryOptions,
  type UseSuspenseQueryResult,
  useMutation,
  useQuery,
  useQueryClient,
  useSuspenseQuery,
} from "@tanstack/react-query";
import { __ev_call, getFnId } from "./transport";

/**
 * A server function stub as generated by the build-tools loader.
 */
export type ServerFunction<TArgs extends unknown[], TResponse> = (
  ...args: TArgs
) => Promise<TResponse>;

/**
 * The interface for a single server function's query proxy.
 */
export interface QueryProxyHandler<TArgs extends unknown[], TResponse> {
  /** Call the server function directly. */
  (...args: TArgs): Promise<TResponse>;

  /** Use as a standard TanStack Query. */
  useQuery(
    ...args: [
      ...args: TArgs,
      options?: Omit<UseQueryOptions<TResponse, Error>, "queryKey" | "queryFn">,
    ]
  ): UseQueryResult<TResponse, Error>;

  /** Use as a TanStack Suspense Query. */
  useSuspenseQuery(
    ...args: [
      ...args: TArgs,
      options?: Omit<
        UseSuspenseQueryOptions<TResponse, Error>,
        "queryKey" | "queryFn"
      >,
    ]
  ): UseSuspenseQueryResult<TResponse, Error>;

  /** Returns standard TanStack Query options. */
  queryOptions(
    ...args: [
      ...args: TArgs,
      options?: Omit<UseQueryOptions<TResponse, Error>, "queryKey" | "queryFn">,
    ]
  ): UseQueryOptions<TResponse, Error> & {
    queryKey: unknown[];
    queryFn: () => Promise<TResponse>;
  };

  /** Returns the query key for this function and arguments. */
  queryKey(...args: TArgs): unknown[];

  /** Invalidate cached queries for this function. */
  invalidate(...args: TArgs): void;
}

/**
 * The interface for a single server function's mutation proxy.
 */
export interface MutationProxyHandler<TVariables, TResponse> {
  /** Call the server function directly. */
  (variables: TVariables): Promise<TResponse>;

  /** Use as a TanStack Mutation. */
  useMutation(
    options?: Omit<
      UseMutationOptions<TResponse, Error, TVariables>,
      "mutationFn"
    > & {
      /** Server functions whose queries should be invalidated on success. */
      invalidates?: ((...args: unknown[]) => unknown)[];
    },
  ): UseMutationResult<TResponse, Error, TVariables>;

  /** Returns standard TanStack Mutation options. */
  mutationOptions(
    options?: Omit<
      UseMutationOptions<TResponse, Error, TVariables>,
      "mutationFn"
    >,
  ): UseMutationOptions<TResponse, Error, TVariables> & {
    mutationFn: (variables: TVariables) => Promise<TResponse>;
  };
}

/**
 * A recursive proxy that maps property access to server function stubs.
 */
export type QueryProxy<TModule> = {
  [K in keyof TModule]: TModule[K] extends ServerFunction<
    infer TArgs,
    infer TResponse
  >
    ? QueryProxyHandler<TArgs, TResponse>
    : QueryProxy<TModule[K]>;
};

export type MutationProxy<TModule> = {
  [K in keyof TModule]: TModule[K] extends ServerFunction<
    infer TVars,
    infer TResponse
  >
    ? MutationProxyHandler<TVars, TResponse>
    : MutationProxy<TModule[K]>;
};

function splitArgsAndOptions(rawArgs: unknown[]): {
  args: unknown[];
  options?: Record<string, unknown>;
} {
  const last = rawArgs[rawArgs.length - 1];
  if (
    rawArgs.length > 0 &&
    last != null &&
    typeof last === "object" &&
    !Array.isArray(last) &&
    // Plain object check — rules out class instances, Dates, etc.
    Object.getPrototypeOf(last) === Object.prototype
  ) {
    return {
      args: rawArgs.slice(0, -1),
      options: last as Record<string, unknown>,
    };
  }
  return { args: rawArgs };
}

function createHandler(fn: ServerFunction<unknown[], unknown>, path: string[]) {
  const fnId = getFnId(fn);
  return {
    useQuery: (...rawArgs: unknown[]) => {
      const { args, options } = splitArgsAndOptions(rawArgs);
      return useQuery({
        ...options,
        queryKey: [fnId || path.join("."), ...args],
        queryFn: ({ signal }) =>
          __ev_call(fnId || path.join("."), args, { signal }),
      });
    },
    useSuspenseQuery: (...rawArgs: unknown[]) => {
      const { args, options } = splitArgsAndOptions(rawArgs);
      return useSuspenseQuery({
        ...options,
        queryKey: [fnId || path.join("."), ...args],
        queryFn: ({ signal }) =>
          __ev_call(fnId || path.join("."), args, { signal }),
      });
    },
    useMutation: (
      options?: Omit<
        UseMutationOptions<unknown, Error, unknown>,
        "mutationFn"
      > & {
        invalidates?: ((...args: unknown[]) => unknown)[];
      },
    ) => {
      const queryClient = useQueryClient();
      const { invalidates, ...restOptions } = options ?? {};
      return useMutation({
        ...restOptions,
        mutationFn: (variables: unknown) => fn(variables),
        onSuccess: (...onSuccessArgs) => {
          if (invalidates) {
            for (const target of invalidates) {
              const targetId = getFnId(target);
              if (targetId) {
                queryClient.invalidateQueries({ queryKey: [targetId] });
              }
            }
          }
          (
            restOptions as UseMutationOptions<unknown, Error, unknown>
          )?.onSuccess?.(...onSuccessArgs);
        },
      });
    },
    queryOptions: (...rawArgs: unknown[]) => {
      const { args, options } = splitArgsAndOptions(rawArgs);
      return {
        ...options,
        queryKey: [fnId || path.join("."), ...args],
        queryFn: ({ signal }: { signal?: AbortSignal }) =>
          __ev_call(fnId || path.join("."), args, { signal }),
      };
    },
    mutationOptions: (
      options?: Omit<UseMutationOptions<unknown, Error, unknown>, "mutationFn">,
    ) => {
      return {
        ...options,
        mutationFn: (variables: unknown) => fn(variables),
      };
    },
    queryKey: (...args: unknown[]) => {
      return [fnId || path.join("."), ...args];
    },
    invalidate: (...args: unknown[]) => {
      const queryClient = useQueryClient();
      queryClient.invalidateQueries({
        queryKey: [fnId || path.join("."), ...args],
      });
    },
    path: path.join("."),
  };
}

function createProxy(
  type: "query" | "mutation",
  source?: unknown,
  path: string[] = [],
): unknown {
  const target = source ?? (() => {});
  return new Proxy(target as object, {
    get(_target, prop: string) {
      const newPath = [...path, prop];
      const val = source
        ? (source as Record<string, unknown>)[prop]
        : undefined;

      // If we have a source and this is a function, return the handler
      if (typeof val === "function") {
        return createHandler(
          val as unknown as ServerFunction<unknown[], unknown>,
          newPath,
        );
      }

      // Otherwise return a nested proxy
      return createProxy(type, val, newPath);
    },
    apply(_target, _thisArg, args) {
      const fn = args[0] as unknown as ServerFunction<unknown[], unknown>;
      if (typeof fn === "function") {
        return createHandler(fn, path);
      }
      return fn; // Fallback
    },
  });
}

/**
 * Create a type-safe query proxy for a module or object.
 */
export function createQueryProxy<T>(source?: T): QueryProxy<T> {
  return createProxy("query", source) as QueryProxy<T>;
}

/**
 * Create a type-safe mutation proxy for a module or object.
 */
export function createMutationProxy<T>(source?: T): MutationProxy<T> {
  return createProxy("mutation", source) as MutationProxy<T>;
}

/**
 * The global query proxy/wrapper.
 * @example
 * const { data } = query(getUsers).useQuery();
 * // or with a typed proxy:
 * const api = createQueryProxy(getUsersModule);
 * const { data } = api.getUsers.useQuery();
 */
export const query = createProxy("query") as (<
  TArgs extends unknown[],
  TResponse,
>(
  fn: ServerFunction<TArgs, TResponse>,
) => QueryProxyHandler<TArgs, TResponse>) &
  QueryProxy<Record<string, unknown>>;

/**
 * The global mutation proxy/wrapper.
 * @example const { mutate } = mutation(createUser).useMutation();
 */
export const mutation = createProxy("mutation") as (<TVariables, TResponse>(
  fn: (args: TVariables) => Promise<TResponse>,
) => MutationProxyHandler<TVariables, TResponse>) &
  MutationProxy<Record<string, unknown>>;
